name: CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  # Test job
  tests:
    name: Test unitaire
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      # Set up Maven Cache
      - name: Set up Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
        # Run Tests
      - name: Run Tests
        run: mvn -B test